---
title: 'Ein sehr guter Kommentar aus ...'
subtitle: ''
summary: ''
authors: ["admin"]
date: 2020-03-08
lastmod: 2020-03-08T20:22:10+01:00
categories:
- facebook
tags: []
featured: no
image:
  placement: 1
  caption: ''
  focal_point: 'Smart'
  preview_only: true
slug: ''
---
Ein sehr guter Kommentar aus dem Heise-Forum: 

"Ich sehe keinen Grund für weniger Hysterie:
Die Luft in China ist nachweislich besser geworden - anderswo sicher auch, da ist es aber großflächer und weniger zu messen. Es wird weniger geflogen, und die Kreuzfahrtschiffe stehen still. Die Börse kommt mal auf den Boden der Tatsachen zurück. Der amerikanische Präsident muss Probleme lösen, statt sie wegzulügen, denn das funktioniert mit einem Virus weit schlechter als mit einem Wirtschaftseinbruch. Die Menschen werden gezwungen zu lernen, dass es keine so gute Idee ist, für jeden Scheiß um die Welt zu jetten, und dass man vieles heutzutage euch über Telepräsenz machen kann. Es wird unmissverständlich klar, dass man die Produktion bestimmter Güter auf ausreichend Produzenten verteilen muss, damit es keine Engpässe gibt - siehe z.B. Atemschutzmasken. Das Konzept von Plünderung und Hehlerei mit allen Problemen wird Menschen im Westen bewusst. Vielerorts merken die Leute erst, wie überladen der öffentliche Nahverkehr ist, und dass ein Ausbau nötig wäre, um den Menschen in den Zügen einen gewissen Abstand zu bieten (dann würde auch mehr damit fahren, spätestens wenn die Hysterie irgendwann vorbei ist). Alle Staaten der Welt sehen deutlich die Schwachstellen in ihren Gesundheitssystemen. Vielerorts wird klar, dass die BWL-indoktrinierte Idee, dass ein Krankenhaus Gewinn abwerfen müsse, Irrsinn ist. Wenn irgendwann wirklich mal ein richtig gefährliches Virus kommen sollte oder ein maximal resistentes Bakterium, dann besteht jetzt die Chance besser vorbereitet zu sein. Im Moment befürchte ich aber, ist die Hysterie noch nicht groß genug, sondern das wird so ein Hupfer wie bei der Bankenkrise. Und ja - eigentlich bräuchte man keine Hysterie. Mit Ruhe und Verstand hätte man das alle auch ohne Corona-Hysterie erkennen können und mit den Lösungsansätzen kommen. Aber es gibt leider genug Menschen, die erst bei Hysterie reagieren und fordern, dass sich was ändert."

Siehe https://www.heise.de/forum/iX/News-Kommentare/Kommentar-Etwas-weniger-Corona-Hysterie-bitte/Ich-sehe-keinen-Grund-fuer-weniger-Hysterie/posting-36257043/show/

Die Luft in China ist nachweislich besser geworden - anderswo sicher auch, da ist es aber großflächer und weniger zu messen. Es wird weniger geflogen, und die Kreuzfahrtschiffe stehen still. Die Börse kommt mal auf den Boden der Tatsachen zurück. Trump muss Probleme lösen, statt sie wegzulügen, denn das funktioniert mit einem Virus weit schlechter als mit einem Wirtschaftseinbruch. Die Menschen werden gezwungen zu lernen, dass es keine so gute Idee ist, für jeden Scheiß um die Welt zu jetten, und dass man vieles heutzutage euch über Telepräsenz machen kann. Es wird unmissverständlich klar, dass man die Produktion bestimmter Güter auf ausreichend Produzenten verteilen muss, damit es keine Engpässe gibt - siehe z.B. Atemschutzmasken. Das Konzept von Plünderung und Hehlerei mit allen Problemen wird Menschen im Westen bewusst. Vielerorts merken die Leute erst, wie überladen der öffentliche Nahverkehr ist, und dass ein Ausbau nötig wäre, um den Menschen in den Zügen einen gewissen Abstand zu bieten (dann würde auch mehr damit fahren, spätestens wenn die Hysterie irgendwann vorbei ist). Alle Staaten der Welt sehen deutlich die Schwachstellen in ihren Gesundheitssystemen. Vielerorts wird klar, dass die BWL-indokdrtinierte Idee, dass ein Krankenhaus Gewinn abwerfen müsse, Irrsinn ist. Wenn irgendwann wirklich mal ein richtig gefährliches Virus kommen sollte oder ein maximal resistentes Bakterium, dann besteht jetzt die Chance besser vorbereitet zu sein. Im Moment befürchte ich aber, ist die Hysterie noch nicht groß genug, sondern das wird so ein Hupfer wie bei der Bankenkrise. Und ja - eigentlich bräuchte man keine Hysterie. Mit Ruhe und Verstand hätte man das alle auch ohne Corona-Hysterie erkennen können und mit den Lösungsansätzen kommen. Aber es gibt leider genug Menschen, die erst bei Hysterie reagieren und fordern, dass sich was ändert.
Die Luft in China ist nachweislich besser geworden - anderswo sicher auch, da ist es aber großflächer und weniger zu messen. Es wird weniger geflogen, und die Kreuzfahrtschiffe stehen still. Die Börse kommt mal auf den Boden der Tatsachen zurück. Trump muss Probleme lösen, statt sie wegzulügen, denn das funktioniert mit einem Virus weit schlechter als mit einem Wirtschaftseinbruch. Die Menschen werden gezwungen zu lernen, dass es keine so gute Idee ist, für jeden Scheiß um die Welt zu jetten, und dass man vieles heutzutage euch über Telepräsenz machen kann. Es wird unmissverständlich klar, dass man die Produktion bestimmter Güter auf ausreichend Produzenten verteilen muss, damit es keine Engpässe gibt - siehe z.B. Atemschutzmasken. Das Konzept von Plünderung und Hehlerei mit allen Problemen wird Menschen im Westen bewusst. Vielerorts merken die Leute erst, wie überladen der öffentliche Nahverkehr ist, und dass ein Ausbau nötig wäre, um den Menschen in den Zügen einen gewissen Abstand zu bieten (dann würde auch mehr damit fahren, spätestens wenn die Hysterie irgendwann vorbei ist). Alle Staaten der Welt sehen deutlich die Schwachstellen in ihren Gesundheitssystemen. Vielerorts wird klar, dass die BWL-indokdrtinierte Idee, dass ein Krankenhaus Gewinn abwerfen müsse, Irrsinn ist. Wenn irgendwann wirklich mal ein richtig gefährliches Virus kommen sollte oder ein maximal resistentes Bakterium, dann besteht jetzt die Chance besser vorbereitet zu sein. Im Moment befürchte ich aber, ist die Hysterie noch nicht groß genug, sondern das wird so ein Hupfer wie bei der Bankenkrise. Und ja - eigentlich bräuchte man keine Hysterie. Mit Ruhe und Verstand hätte man das alle auch ohne Corona-Hysterie erkennen können und mit den Lösungsansätzen kommen. Aber es gibt leider genug Menschen, die erst bei Hysterie reagieren und fordern, dass sich was ändert.

